### ISSUE TITLE
How to test on my own LFs

### ISSUE THREAD

**Issue by YingqianWang** [monaen/LightFieldReconstruction#2]
How can I perform test on my own LFs using this released code?

**Comment by monaen** [comment]
To test the performance on your own LFs, you can use the evaluation code, but currently, we only update the spatial evaluation code (evaluation_SpatialSR.py) and the pre-trained model is for (gaussian + nearest-neighbor) downsampling.

We will keep updating the project, but since this one is huge and we do not have a good plan at the very beginning, we have to organize and clean up the entire code at the same time. 

Thanks for your understanding.
Nan
